  
name: CI
on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0
      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: vpbot/vpbot
          tag: dev
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}