name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vpbot:dev
    - name: Docker Publish
      run: |
        docker login docker.pkg.github.com --username ThisDrunkDane ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/thisdrunkdane/vpbot/vpbot:dev
