name: Docker Image CI

on: [push, workflow_dispatch]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build \
          --build-arg GIT_COMMIT=${{ github.sha }} \
          --build-arg BUILD_TIME=$(date +%Y-%m-%d) \
          --file Dockerfile \
          --tag ghcr.io/thisdevdane/vpbot/vpbot:dev \
          . 
    - name: Docker Publish
      run: docker push ghcr.io/thisdevdane/vpbot/vpbot:dev
