name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/thisdrunkdane/vpbot/vpbot:dev
    - name: Docker Publish
      run: docker push docker.pkg.github.com/thisdrunkdane/vpbot/vpbot:dev
